### ISSUE TITLE
django.contrib.sites migrations & testing - IntegrityError

### ISSUE THREAD

**Issue by jensneuhaus** [pydanny/cookiecutter-django#1163]
## Problem

I am working with the django.contrib.sites framework for multi-tenancy reasons. The first Site is created with the cookiecutter migrations in {{cookiecutter.project_slug}}/contrib/sites/migrations.

Besides this one I need to add sites to the backend dynamically. This works in the shell or when used "in production", **but the tests are not running**.

My environment is Django 1.10.7, Python 3.6.0, newest cookiecutter-django 1.10.7.

## Test to reproduce the error

```
class SingleTest(TestCase):
    """ Test the sign_up process of the API endpoint """

    def test_django_site_setup(self):

        Site.objects.create(name="foo", domain="foo.com")
```

## Things fail, when the cookiecutter migrations are used

settings.py:
```
MIGRATION_MODULES = {
    'sites': 'myproject.contrib.sites.migrations'
}
```

(.venv)  $ python manage.py test apps.tenants.test_api.SingleTest:
```
Creating test database for alias 'default'...
E
======================================================================
ERROR: test_django_site_setup (apps.tenants.test_api.SingleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "django_site_pkey"
DETAIL:  Key (id)=(1) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jens/myproject/apps/tenants/models.py", line 44, in create_tenant
    site = Site.objects.create(name=domain, domain=domain)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/jens/myproject/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "django_site_pkey"
DETAIL:  Key (id)=(1) already exists.
```

## Tests are running, when MIGRATION_MODULES is uncommented or if the Django migrations are used

settings.py:
```
MIGRATION_MODULES = {
    'sites': 'django.contrib.sites.migrations'
}
```

(.venv)  $ python manage.py test apps.tenants.test_api.SingleTest:
```
Creating test database for alias 'default'...
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
```

I am not sure it this is a bug or if I am doing something wrong.

**Comment by webyneter** [comment]
@jensneuhaus, 

> My environment is Django 1.10.7, Python 3.6.0, newest cookiecutter-django 1.10.7.

We don't officially support Python 3.6 -- mind trying this out on 3.5 and reporting back?

**Comment by pydanny** [comment]
We also do not provide support for the various django-tenants projects. If changing your python version does not fix the error, I suggest you open a ticket with that projects.
