### ISSUE TITLE
Bug with Not Open Source Licence

### ISSUE THREAD

**Issue by pythdasch** [pydanny/cookiecutter-django#1191]
Traceback (most recent call last):
  File "/usr/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==1.3.0', 'console_scripts', 'cookiecutter')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/cli.py", line 100, in main
    config_file=user_config
  File "/usr/lib/python2.7/dist-packages/cookiecutter/main.py", line 140, in cookiecutter
    output_dir=output_dir
  File "/usr/lib/python2.7/dist-packages/cookiecutter/generate.py", line 327, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/generate.py", line 167, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/home/dsc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/dsc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/dsc/.local/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/dsc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/dsc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "./LICENSE", line 3, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'now'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
  File "./LICENSE", line 3
    Copyright (c) {% now 'utc', '%Y' %}, {{ cookiecutter.author_name }}

When choosing Not Open Source Licence

**Comment by webyneter** [comment]
@pythdasch, we have dropped official support for Python 2.x some time ago -- make sure to invoke `cookiecutter-django` from Python 3.4/3.5.

**Comment by pythdasch** [comment]
Hooo ok ! Thanks :)

**Comment by pythdasch** [comment]
@webyneter I don't see a good doc on installing cookiecutter. If I have to change my bashprofile for installing cookiecutter now it's quite annoying since I'll have to redo it after. Is there a simple way to install a package via cookiecutter ?

**Comment by pydanny** [comment]
`pip3 install cookiecutter`

**Comment by pythdasch** [comment]
Thanks :) Maybe adding it in the doc would worth it ? I installed cookiecutter by apt-get so had to uninstall it and install pip3.

**Comment by webyneter** [comment]
@pythdasch, there's one [in the project's README](https://github.com/pydanny/cookiecutter-django#usage), but one has to admit it is outdated.
