### ISSUE TITLE
Module not found error in Heroku

### ISSUE THREAD

**Issue by manibk31** [pydanny/cookiecutter-django#1576]
File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_comma
nd_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/app/..heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named "'config"

I followed the setup as mentioned in the documentation.  I suspect it's some sort of a sys.path error, but not sure. Any help would be very much appreciated

**Comment by browniebroke** [comment]
Thanks for the bug report @manibk31, in order for us to help best, could you please follow [the issue template](https://github.com/pydanny/cookiecutter-django/issues/new) and especially provide the steps to reproduce? 

This template is there for a reason,  and it would make our investigation _so much_ easier.

Thanks 😄

**Comment by browniebroke** [comment]
Can you check the `LOCAL_APPS` setting in `config/settings/base.py`? The error seems to complain of an extra single quote in the module name `'config`:

```
No module named "'config"
```

**Comment by manibk31** [comment]
My deepest apologies for not having replied in time, and I really appreciate your time and efforts for helping me out. I just checked my code and the problem indeed was with an extra ' near config and once I fixed it its all working fine now. 

Cheers,
Mani :)

**Comment by browniebroke** [comment]
No worries! Someone else had a similar issue recently in #1488 but we couldn't find what caused it. Hopefully, this will help other people in the future 😄

**Comment by mrkp305** [comment]
Ran into a similar issue i think:

I'm trying to deploy using gunicorn and on `gunicorn project.config.wsgi:application`, it returns the following error(s):

```
Traceback (most recent call last):
  File "/home/isppme/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/isppme/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/isppme/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/isppme/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/isppme/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/isppme/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/isppme/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/isppme/isppme_wa/config/wsgi.py", line 36, in <module>
    application = get_wsgi_application()
  File "/home/isppme/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/isppme/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/isppme/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/isppme/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/isppme/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/isppme/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'config'
```

**Comment by TITANHACKY** [comment]
I'm getting error when deploying my app in heroku

2020-09-07T18:54:44.923046+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2020-09-07T18:54:44.923076+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/runpy.py", line 142, in _get_module_details
2020-09-07T18:54:44.923295+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2020-09-07T18:54:44.923337+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/runpy.py", line 109, in _get_module_details
2020-09-07T18:54:44.923540+00:00 app[web.1]:     __import__(pkg_name)
2020-09-07T18:54:44.923546+00:00 app[web.1]:   File "/app/tg_bot/__init__.py", line 62, in <module>
2020-09-07T18:54:44.923706+00:00 app[web.1]:     from tg_bot.config import Development as Config
2020-09-07T18:54:44.923727+00:00 app[web.1]: ModuleNotFoundError: No module named 'tg_bot.config'
2020-09-07T18:54:45.006882+00:00 heroku[web.1]: Process exited with status 1
2020-09-07T18:54:45.057486+00:00 heroku[web.1]: State changed from starting to crashed

But i had placed the config file in tg_bot folder but it says that no module named tg_bot.config
