### ISSUE TITLE
Celerybeat container fails to start 

### ISSUE THREAD

**Issue by jcapogna** [pydanny/cookiecutter-django#1793]
## What happened?

Using an out of the box cookiecutter-django project, with default generation options, except for enabling docker and celery. When running the project, the celerybeat container fails to start. 

## What should've happened instead?

The celerybeat container should start successfully. 

## Steps to reproduce

Project generation options (all default, except enable docker and celery)
```
project_name [My Awesome Project]: testcelery
project_slug [testcelery]:
description [Behold My Awesome Project!]:
author_name [Daniel Roy Greenfeld]:
domain_name [example.com]:
email [daniel-roy-greenfeld@example.com]:
version [0.1.0]:
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]:
timezone [UTC]:
windows [n]:
use_pycharm [n]:
use_docker [n]: y
Select postgresql_version:
1 - 10.4
2 - 10.3
3 - 10.2
4 - 10.1
5 - 9.6
6 - 9.5
7 - 9.4
8 - 9.3
Choose from 1, 2, 3, 4, 5, 6, 7, 8 [1]:
Select js_task_runner:
1 - None
2 - Gulp
Choose from 1, 2 [1]:
custom_bootstrap_compilation [n]:
use_compressor [n]:
use_celery [n]: y
use_mailhog [n]:
use_sentry [n]:
use_whitenoise [n]:
use_heroku [n]:
use_travisci [n]:
keep_local_envs_in_vcs [y]:
debug [n]:
```
celerybeat logs from docker up

```
celerybeat_1    | PostgreSQL is available
celerybeat_1    | celery beat v4.2.1 (windowlicker) is starting.
celerybeat_1    | __    -    ... __   -        _
celerybeat_1    | LocalTime -> 2018-09-07 21:29:49
celerybeat_1    | Configuration ->
celerybeat_1    |     . broker -> redis://redis:6379/0
celerybeat_1    |     . loader -> celery.loaders.app.AppLoader
celerybeat_1    |     . scheduler -> celery.beat.PersistentScheduler
celerybeat_1    |     . db -> celerybeat-schedule
celerybeat_1    |     . logfile -> [stderr]@%INFO
celerybeat_1    |     . maxinterval -> 5.00 minutes (300s)
celerybeat_1    | [2018-09-07 21:29:49,944: INFO/MainProcess] beat: Starting...
celerybeat_1    | [2018-09-07 21:29:49,973: ERROR/MainProcess] Removing corrupted schedule file 'celerybeat-schedule': error(22, 'Invalid argument')
celerybeat_1    | Traceback (most recent call last):
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
celerybeat_1    |     return obj.__dict__[self.__name__]
celerybeat_1    | KeyError: 'scheduler'
celerybeat_1    |
celerybeat_1    | During handling of the above exception, another exception occurred:
celerybeat_1    |
celerybeat_1    | Traceback (most recent call last):
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 476, in setup_schedule
celerybeat_1    |     self._store = self._open_schedule()
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 466, in _open_schedule
celerybeat_1    |     return self.persistence.open(self.schedule_filename, writeback=True)
celerybeat_1    |   File "/usr/local/lib/python3.6/shelve.py", line 243, in open
celerybeat_1    |     return DbfilenameShelf(filename, flag, protocol, writeback)
celerybeat_1    |   File "/usr/local/lib/python3.6/shelve.py", line 227, in __init__
celerybeat_1    |     Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
celerybeat_1    |   File "/usr/local/lib/python3.6/dbm/__init__.py", line 94, in open
celerybeat_1    |     return mod.open(file, flag, mode)
celerybeat_1    | _gdbm.error: [Errno 22] Invalid argument
celerybeat_1    | [2018-09-07 21:29:50,008: CRITICAL/MainProcess] beat raised exception <class '_gdbm.error'>: error(22, 'Invalid argument')
celerybeat_1    | Traceback (most recent call last):
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
celerybeat_1    |     return obj.__dict__[self.__name__]
celerybeat_1    | KeyError: 'scheduler'
celerybeat_1    |
celerybeat_1    | During handling of the above exception, another exception occurred:
celerybeat_1    |
celerybeat_1    | Traceback (most recent call last):
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 476, in setup_schedule
celerybeat_1    |     self._store = self._open_schedule()
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 466, in _open_schedule
celerybeat_1    |     return self.persistence.open(self.schedule_filename, writeback=True)
celerybeat_1    |   File "/usr/local/lib/python3.6/shelve.py", line 243, in open
celerybeat_1    |     return DbfilenameShelf(filename, flag, protocol, writeback)
celerybeat_1    |   File "/usr/local/lib/python3.6/shelve.py", line 227, in __init__
celerybeat_1    |     Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
celerybeat_1    |   File "/usr/local/lib/python3.6/dbm/__init__.py", line 94, in open
celerybeat_1    |     return mod.open(file, flag, mode)
celerybeat_1    | _gdbm.error: [Errno 22] Invalid argument
celerybeat_1    |
celerybeat_1    | During handling of the above exception, another exception occurred:
celerybeat_1    |
celerybeat_1    | Traceback (most recent call last):
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 109, in start_scheduler
celerybeat_1    |     service.start()
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 579, in start
celerybeat_1    |     humanize_seconds(self.scheduler.max_interval))
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
celerybeat_1    |     value = obj.__dict__[self.__name__] = self.__get(obj)
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 623, in scheduler
celerybeat_1    |     return self.get_scheduler()
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 618, in get_scheduler
celerybeat_1    |     lazy=lazy,
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 458, in __init__
celerybeat_1    |     Scheduler.__init__(self, *args, **kwargs)
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 225, in __init__
celerybeat_1    |     self.setup_schedule()
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 484, in setup_schedule
celerybeat_1    |     self._store = self._destroy_open_corrupted_schedule(exc)
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 472, in _destroy_open_corrupted_schedule
celerybeat_1    |     return self._open_schedule()
celerybeat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 466, in _open_schedule
celerybeat_1    |     return self.persistence.open(self.schedule_filename, writeback=True)
celerybeat_1    |   File "/usr/local/lib/python3.6/shelve.py", line 243, in open
celerybeat_1    |     return DbfilenameShelf(filename, flag, protocol, writeback)
celerybeat_1    |   File "/usr/local/lib/python3.6/shelve.py", line 227, in __init__
celerybeat_1    |     Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
celerybeat_1    |   File "/usr/local/lib/python3.6/dbm/__init__.py", line 94, in open
celerybeat_1    |     return mod.open(file, flag, mode)
celerybeat_1    | _gdbm.error: [Errno 22] Invalid argument
celerybeat_1    | [2018-09-07 21:29:50,023: WARNING/MainProcess] Traceback (most recent call last):
celerybeat_1    | [2018-09-07 21:29:50,025: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
celerybeat_1    | [2018-09-07 21:29:50,027: WARNING/MainProcess] return obj.__dict__[self.__name__]
celerybeat_1    | [2018-09-07 21:29:50,027: WARNING/MainProcess] KeyError
celerybeat_1    | [2018-09-07 21:29:50,030: WARNING/MainProcess] :
celerybeat_1    | [2018-09-07 21:29:50,032: WARNING/MainProcess] 'scheduler'
celerybeat_1    | [2018-09-07 21:29:50,035: WARNING/MainProcess] During handling of the above exception, another exception occurred:
celerybeat_1    | [2018-09-07 21:29:50,035: WARNING/MainProcess] Traceback (most recent call last):
celerybeat_1    | [2018-09-07 21:29:50,035: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 476, in setup_schedule
celerybeat_1    | [2018-09-07 21:29:50,040: WARNING/MainProcess] self._store = self._open_schedule()
celerybeat_1    | [2018-09-07 21:29:50,042: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 466, in _open_schedule
celerybeat_1    | [2018-09-07 21:29:50,044: WARNING/MainProcess] return self.persistence.open(self.schedule_filename, writeback=True)
celerybeat_1    | [2018-09-07 21:29:50,054: WARNING/MainProcess] File "/usr/local/lib/python3.6/shelve.py", line 243, in open
celerybeat_1    | [2018-09-07 21:29:50,070: WARNING/MainProcess] return DbfilenameShelf(filename, flag, protocol, writeback)
celerybeat_1    | [2018-09-07 21:29:50,070: WARNING/MainProcess] File "/usr/local/lib/python3.6/shelve.py", line 227, in __init__
celerybeat_1    | [2018-09-07 21:29:50,072: WARNING/MainProcess] Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
celerybeat_1    | [2018-09-07 21:29:50,073: WARNING/MainProcess] File "/usr/local/lib/python3.6/dbm/__init__.py", line 94, in open
celerybeat_1    | [2018-09-07 21:29:50,082: WARNING/MainProcess] return mod.open(file, flag, mode)
celerybeat_1    | [2018-09-07 21:29:50,085: WARNING/MainProcess] _gdbm
celerybeat_1    | [2018-09-07 21:29:50,086: WARNING/MainProcess] .
celerybeat_1    | [2018-09-07 21:29:50,087: WARNING/MainProcess] error
celerybeat_1    | [2018-09-07 21:29:50,088: WARNING/MainProcess] :
celerybeat_1    | [2018-09-07 21:29:50,090: WARNING/MainProcess] [Errno 22] Invalid argument
celerybeat_1    | [2018-09-07 21:29:50,091: WARNING/MainProcess] During handling of the above exception, another exception occurred:
celerybeat_1    | [2018-09-07 21:29:50,093: WARNING/MainProcess] Traceback (most recent call last):
celerybeat_1    | [2018-09-07 21:29:50,095: WARNING/MainProcess] File "/usr/local/bin/celery", line 11, in <module>
celerybeat_1    | [2018-09-07 21:29:50,098: WARNING/MainProcess] sys.exit(main())
celerybeat_1    | [2018-09-07 21:29:50,101: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
celerybeat_1    | [2018-09-07 21:29:50,102: WARNING/MainProcess] _main()
celerybeat_1    | [2018-09-07 21:29:50,103: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
celerybeat_1    | [2018-09-07 21:29:50,105: WARNING/MainProcess] cmd.execute_from_commandline(argv)
celerybeat_1    | [2018-09-07 21:29:50,109: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
celerybeat_1    | [2018-09-07 21:29:50,110: WARNING/MainProcess] super(CeleryCommand, self).execute_from_commandline(argv)))
celerybeat_1    | [2018-09-07 21:29:50,114: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
celerybeat_1    | [2018-09-07 21:29:50,117: WARNING/MainProcess] return self.handle_argv(self.prog_name, argv[1:])
celerybeat_1    | [2018-09-07 21:29:50,118: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
celerybeat_1    | [2018-09-07 21:29:50,120: WARNING/MainProcess] return self.execute(command, argv)
celerybeat_1    | [2018-09-07 21:29:50,123: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
celerybeat_1    | [2018-09-07 21:29:50,130: WARNING/MainProcess] ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
celerybeat_1    | [2018-09-07 21:29:50,132: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 279, in run_from_argv
celerybeat_1    | [2018-09-07 21:29:50,134: WARNING/MainProcess] sys.argv if argv is None else argv, command)
celerybeat_1    | [2018-09-07 21:29:50,136: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 363, in handle_argv
celerybeat_1    | [2018-09-07 21:29:50,138: WARNING/MainProcess] return self(*args, **options)
celerybeat_1    | [2018-09-07 21:29:50,141: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__
celerybeat_1    | [2018-09-07 21:29:50,142: WARNING/MainProcess] ret = self.run(*args, **kwargs)
celerybeat_1    | [2018-09-07 21:29:50,146: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
celerybeat_1    | [2018-09-07 21:29:50,154: WARNING/MainProcess] return beat().run()
celerybeat_1    | [2018-09-07 21:29:50,156: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 81, in run
celerybeat_1    | [2018-09-07 21:29:50,157: WARNING/MainProcess] self.start_scheduler()
celerybeat_1    | [2018-09-07 21:29:50,166: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 109, in start_scheduler
celerybeat_1    | [2018-09-07 21:29:50,168: WARNING/MainProcess] service.start()
celerybeat_1    | [2018-09-07 21:29:50,169: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 579, in start
celerybeat_1    | [2018-09-07 21:29:50,171: WARNING/MainProcess] humanize_seconds(self.scheduler.max_interval))
celerybeat_1    | [2018-09-07 21:29:50,172: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
celerybeat_1    | [2018-09-07 21:29:50,174: WARNING/MainProcess] value = obj.__dict__[self.__name__] = self.__get(obj)
celerybeat_1    | [2018-09-07 21:29:50,176: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 623, in scheduler
celerybeat_1    | [2018-09-07 21:29:50,182: WARNING/MainProcess] return self.get_scheduler()
celerybeat_1    | [2018-09-07 21:29:50,183: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 618, in get_scheduler
celerybeat_1    | [2018-09-07 21:29:50,184: WARNING/MainProcess] lazy=lazy,
celerybeat_1    | [2018-09-07 21:29:50,189: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 458, in __init__
celerybeat_1    | [2018-09-07 21:29:50,190: WARNING/MainProcess] Scheduler.__init__(self, *args, **kwargs)
celerybeat_1    | [2018-09-07 21:29:50,191: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 225, in __init__
celerybeat_1    | [2018-09-07 21:29:50,192: WARNING/MainProcess] self.setup_schedule()
celerybeat_1    | [2018-09-07 21:29:50,193: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 484, in setup_schedule
celerybeat_1    | [2018-09-07 21:29:50,195: WARNING/MainProcess] self._store = self._destroy_open_corrupted_schedule(exc)
celerybeat_1    | [2018-09-07 21:29:50,196: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 472, in _destroy_open_corrupted_schedule
celerybeat_1    | [2018-09-07 21:29:50,198: WARNING/MainProcess] return self._open_schedule()
celerybeat_1    | [2018-09-07 21:29:50,200: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 466, in _open_schedule
celerybeat_1    | [2018-09-07 21:29:50,203: WARNING/MainProcess] return self.persistence.open(self.schedule_filename, writeback=True)
celerybeat_1    | [2018-09-07 21:29:50,212: WARNING/MainProcess] File "/usr/local/lib/python3.6/shelve.py", line 243, in open
celerybeat_1    | [2018-09-07 21:29:50,214: WARNING/MainProcess] return DbfilenameShelf(filename, flag, protocol, writeback)
celerybeat_1    | [2018-09-07 21:29:50,219: WARNING/MainProcess] File "/usr/local/lib/python3.6/shelve.py", line 227, in __init__
celerybeat_1    | [2018-09-07 21:29:50,221: WARNING/MainProcess] Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
celerybeat_1    | [2018-09-07 21:29:50,222: WARNING/MainProcess] File "/usr/local/lib/python3.6/dbm/__init__.py", line 94, in open
celerybeat_1    | [2018-09-07 21:29:50,223: WARNING/MainProcess] return mod.open(file, flag, mode)
celerybeat_1    | [2018-09-07 21:29:50,224: WARNING/MainProcess] _gdbm
celerybeat_1    | [2018-09-07 21:29:50,224: WARNING/MainProcess] .
celerybeat_1    | [2018-09-07 21:29:50,226: WARNING/MainProcess] error
celerybeat_1    | [2018-09-07 21:29:50,227: WARNING/MainProcess] :
celerybeat_1    | [2018-09-07 21:29:50,233: WARNING/MainProcess] [Errno 22] Invalid argument
testcelery_celerybeat_1 exited with code 1
```

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Project generation options)
[//]: # (* Logs)

**Comment by jcapogna** [comment]
@browniebroke 

I'm not sure to be honest. I debugged this the best I could. 

As far as I can tell celerybeat code detects a bad schedule file, deletes it, and then carries on. So a bad schedule file shouldn't be a problem. Granted, it sure seems to be based on the logs. 

I also tried deleting the schedule file in the Docker start file right before celery beat is started. That got rid of the initial logs mentioning removing the corrupted schedule file, but the rest of the errors persisted.

**Comment by robrivas** [comment]
> @browniebroke
> 
> I'm not sure to be honest. I debugged this the best I could.
> 
> As far as I can tell the celerybeat code detects a bad schedule file, deletes it, and then carries on (https://github.com/celery/celery/blob/v4.2.1/celery/beat.py#L484). So a bad schedule file shouldn't be a problem. Granted, it sure seems to be based on the logs.
> 
> I also tried deleting the schedule file in the Docker start file right before celery beat is started ( here https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/celery/beat/start#L7). That got rid of the initial logs mentioning removing the corrupted schedule file, but the rest of the errors persisted.

Also tried same thing, removing that line did not help really.

**Comment by EliAndrewC** [comment]
I got exactly the same error on a Vagrant dev environment.  Celery uses dbm for persistent storage, which is built on top of the gdbm C library. Some testing has revealed that this works when creating or opening files on a native filesystem but not on a mounted filesystem. For example, here's what I was seeing on my Vagrant environment:

```python
>>> import dbm
>>> db = dbm.open('/tmp/foo.db', 'c')
>>> db = dbm.open('/home/vagrant/reggie-formula/foo.db', 'c')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 22] Invalid argument
```

This ``Invalid argument`` error matches what I was getting when starting Celerybeat, which seems to be the exact stacktrace documented above.

Our fix in our Vagrant project was the change the Celery configuration to store the scheduler db file in a native filesystem instead of a mounted filesystem.  We happened to use ``/tmp``, though it could have gone anywhere that wasn't mounted.

**Comment by xgenvn** [comment]
Getting rid of this error by changing `start` script under `.local/django/celery/beat`:
```
mkdir -p /var/run/celery/
celery -A apps.taskapp beat -l INFO -s /var/run/celery/beat-schedule
```
However, I'm not sure this is the correct fix. After reading  the celery configuration, perhaps we config  django-celery-beat and use such provider for the beat-scheduler.
Reference: http://docs.celeryproject.org/en/latest/userguide/configuration.html#beat-settings-celery-beat

**Comment by Hey-tom** [comment]
Has anyone got a fix for this issue? I've spent a week trying to rectify

**Comment by maro99** [comment]
help.....killl me.....

**Comment by jcapogna** [comment]
@Hey-tom  and @maro99 

Have either of you tried the solution posted by @xgenvn?

I'm not doing any active Django development right now, otherwise I'd try this out.

**Comment by xgenvn** [comment]
@Hey-tom @maro99 

Add `django_celery_beat==1.3.0 # https://github.com/celery/django-celery-beat` to your `base.txt`

And change `compose/local/django/celery/beat/start`:
```
rm -f './celerybeat.pid'
celery -A apps.taskapp beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
```

**Comment by spool** [comment]
@xgenvn in case this is relevant: I ended up here with a different issue (I upgraded to python 3.7 and ran into this https://github.com/celery/celery/issues/4849) but *hopefully* a new release will come out soon as a fix for various issues https://github.com/celery/celery/issues/5180

**Comment by browniebroke** [comment]
The template now uses django-celery-beat as scheduler out of the box in #2084, which should avoid this from happening. Closing this.
