### ISSUE TITLE
botocore.exceptions.ClientError in Production  when running Collectstatic

### ISSUE THREAD

**Issue by emilepetrone** [pydanny/cookiecutter-django#1885]
## What happened?
I am trying to deploy a project to AWS, pushing my static files to S3, and when I run `collectstatic` in prod, I am getting the following error - 

`docker-compose -f production.yml run --rm django python manage.py collectstatic --no-input`

returns 

`botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied`

I was on the phone with AWS for almost an hour yesterday to ensure nothing was going on with S3, a permissions error, or bucket issue and we are sure it wasn't on AWS. So I'm starting to think there is a bug in the libraries that `collectstatic` references. As I'm going through it, I want to make sure I'm the only one. If so then its something on my end.

Has anyone else run into a similar auth issue? 

## What should've happened instead?

This should authenticate and copy the static files to the S3 bucket. 

## Steps to reproduce

* Copy your AWS creds & bucket name into `.envs/.production/.django`
* `DJANGO_READ_DOT_ENV_FILE` is commented out
* Run `docker-compose -f production.yml run --rm django python manage.py collectstatic --no-input`
* The Static settings in `config/settings/production.py` are the default:

```
# STATIC
# ------------------------

STATICFILES_STORAGE = 'config.settings.production.StaticRootS3Boto3Storage'
STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/static/'

# MEDIA
# ------------------------------------------------------------------------------

# region http://stackoverflow.com/questions/10390244/
# Full-fledge class: https://stackoverflow.com/a/18046120/104731
from storages.backends.s3boto3 import S3Boto3Storage  # noqa E402


class StaticRootS3Boto3Storage(S3Boto3Storage):
    location = 'static'


class MediaRootS3Boto3Storage(S3Boto3Storage):
    location = 'media'
    file_overwrite = False


# endregion
DEFAULT_FILE_STORAGE = 'config.settings.production.MediaRootS3Boto3Storage'
MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/'
```

## My package versions are :
 
```
boto3==1.9.63
botocore==1.12.63
s3transfer==0.1.13

Collectfast==0.6.2  # https://github.com/antonagestam/collectfast
django-storages[boto3]==1.7.1  # https://github.com/jschneier/django-storages
```

## The full error
Here is the key part:

UserWarning: The default behavior of S3Boto3Storage is insecure and will change in django-storages 2.0. By default files and new buckets are saved with an ACL of 'public-read' (globally publicly readable). Version 2.0 will default to using the bucket's ACL. To opt into the new behavior set AWS_DEFAULT_ACL = None, otherwise to silence this warning explicitly set AWS_DEFAULT_ACL.
  "The default behavior of S3Boto3Storage is insecure and will change "

```
docker-compose -f production.yml run --rm django python manage.py collectstatic --no-input
WARNING: Found orphan containers (mom_postgres_1, mom_mailhog_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting mom_redis_1 ... done
PostgreSQL is available
DEBUG 2018-12-13 14:55:10,841 base 1 140542999473032 Configuring Raven for host: https://sentry.io
DEBUG 2018-12-13 14:55:10,845 base 1 140542999473032 Configuring Raven for host: https://sentry.io
/usr/local/lib/python3.6/site-packages/storages/backends/s3boto3.py:282: UserWarning: The default behavior of S3Boto3Storage is insecure and will change in django-storages 2.0. By default files and new buckets are saved with an ACL of 'public-read' (globally publicly readable). Version 2.0 will default to using the bucket's ACL. To opt into the new behavior set AWS_DEFAULT_ACL = None, otherwise to silence this warning explicitly set AWS_DEFAULT_ACL.
  "The default behavior of S3Boto3Storage is insecure and will change "
Ignored error in Collectfast:
Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.
--> Continuing using default collectstatic.
Copying '/app/mom/static/js/project.js'
DEBUG 2018-12-13 14:55:12,775 base 1 140542999473032 Sending message of length 9501 to https://sentry.io/api/1314322/store/
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/collectfast/management/commands/collectstatic.py", line 72, in handle
    super(Command, self).handle(**options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 189, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.6/site-packages/collectfast/management/commands/collectstatic.py", line 63, in collect
    ret = super(Command, self).collect()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/usr/local/lib/python3.6/site-packages/collectfast/management/commands/collectstatic.py", line 111, in copy_file
    self.do_copy_file(args)
  File "/usr/local/lib/python3.6/site-packages/collectfast/management/commands/collectstatic.py", line 100, in do_copy_file
    path, prefixed_path, source_storage)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 49, in save
    return self._save(name, content)
  File "/usr/local/lib/python3.6/site-packages/storages/backends/s3boto3.py", line 506, in _save
    self._save_content(obj, content, parameters=parameters)
  File "/usr/local/lib/python3.6/site-packages/storages/backends/s3boto3.py", line 521, in _save_content
    obj.upload_fileobj(content, ExtraArgs=put_parameters)
  File "/usr/local/lib/python3.6/site-packages/boto3/s3/inject.py", line 621, in object_upload_fileobj
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/usr/local/lib/python3.6/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.6/site-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/lib/python3.6/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 624, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
Sentry is attempting to send 1 pending error messages

```

## What I've verified:
* I can create a client in boto3, and upload a file

```
s3 = boto3.client('s3', aws_access_key_id='xxxxx', aws_secret_access_key='yyyy')
with open('README.rst', 'rb') as f:
  s3.upload_fileobj(f, 'bucket', 'README.rst')
```

**Comment by emilepetrone** [comment]
The solution is to put the following in your settings:

`AWS_DEFAULT_ACL = None`

Is this something that should be committed into the repo? 

One concern - the following is what you get as it runs - 

```
django_1  | /usr/local/lib/python3.6/site-packages/collectfast/management/commands/collectstatic.py:39: UserWarning: Collectfast does not work properly without `preload_metadata` set to `True` on the storage class. Try setting `AWS_PRELOAD_METADATA` to `True`. Overriding `storage.preload_metadata` and continuing.
django_1  |   "Collectfast does not work properly without "
django_1  | Ignored error in Collectfast:
django_1  | Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.
django_1  | --> Continuing using default collectstatic.
django_1  | Copying '/app/mom/static/js/project.js'
django_1  | Ignored error in Collectfast:
django_1  | Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.
django_1  | --> Continuing using default collectstatic.
django_1  | Copying '/app/mom/static/css/project.css'
```

So it is ignoring an error but does copy the files into S3.

**Comment by luzfcb** [comment]
Thank's for pointing this out.

the `AWS_DEFAULT_ACL` behavior of django-storages changed in
https://github.com/jschneier/django-storages/commit/8771ae74471177d9690363b7d72905f89cbad9f0 and this went unnoticed by us.

Please, can you send a pull-request including this variable, and a comment with the link to the django-storages documentation. Be sure to include your name in CONTRIBUTORS.rst

If you find any other inconsistency, feel free to contribute.

**Comment by emilepetrone** [comment]
Will do

**Comment by ihonomic** [comment]
core.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

Similar to this, I'm getting a 404
