### ISSUE TITLE
Travis + Docker result in broken build on CI

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#2100]
## What happened?

Try to generate a project with Docker and Tarvis enabled, the tarvis config is not suitable and fails the build:

<details>
  <summary>Build logs</summary>
  
```
[0Ktravis_fold:end:install
[0Ktravis_time:start:183a4568
[0K$ pytest
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/environ/environ.py", line 273, in get_value
    value = self.ENVIRON[var]
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATABASE_URL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 63, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 207, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 687, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 895, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 851, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pytest_django/plugin.py", line 333, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/browniebroke/cc-dj-tests/config/settings/test.py", line 5, in <module>
    from .base import *  # noqa
  File "/home/travis/build/browniebroke/cc-dj-tests/config/settings/base.py", line 44, in <module>
    DATABASES = {"default": env.db("DATABASE_URL")}
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/environ/environ.py", line 204, in db_url
    return self.db_url_config(self.get_value(var, default=default), engine=engine)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/environ/environ.py", line 277, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable
travis_time:end:183a4568:start=1559838789069844257,finish=1559838789825801676,duration=755957419
[0K[31;1mThe command "pytest" exited with 1.[0m



Done. Your build exited with 1.
```
</details>

We should provide a suitable config when Docker is selected with Travis.

## How to fix this?

Generate a project with the 2 options enabled, push it to Github with Travis and make the build pass by running the appropriate docker commands instead of bare metals ones.

**Comment by kanusek** [comment]
I reverted the database config referenced by @wandering-tales on #1541. 
And added this to .travis.yml
```
before_script:
      - psql -c 'create database {{cookiecutter.project_slug}};' -U postgres
```

After making these changes my travis build passed.

**Comment by step21** [comment]
I have a version of this that works for gitlab ci. Not sure if that would work with travis though.

**Comment by kanusek** [comment]
I would be interested to see your gitlab config

**Comment by step21** [comment]
This works with docker-in-docker and probably requires docker to run in privileged mode, and requires an image with docker-compose (see below).

```
image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - build
  - start
  - test
  
build:
  stage: build
  image: tiangolo/docker-with-compose
  script:
    - docker-compose -f local.yml build

start:
  stage: start
  image: tiangolo/docker-with-compose
  script:
    - docker-compose -f local.yml up -d
    - docker-compose -f local.yml down -v

test:
  stage: test
  image: tiangolo/docker-with-compose
  script:
    - docker-compose run django coverage run -m pytest
  allow_failure: true
```

**Comment by wandering-tales** [comment]
> I reverted the database config referenced by @wandering-tales on #1541.
> And added this to .travis.yml
> 
> ```
> before_script:
>       - psql -c 'create database {{cookiecutter.project_slug}};' -U postgres
> ```
> 
> After making these changes my travis build passed.

Actually `pytest` should take care by itself to create a database for testing, if the configured one is missing.

In my `.travis.yml` I didn't have to explicitly create the database.

**Comment by step21** [comment]
Are you sure pytest creates psql databases? Maybe it just falls back to sqlite?

**Comment by wandering-tales** [comment]
It could never be a SQLite database as in the `DATABASE_URL` setting I'm explicitly using the standard `libpq` connection string to connect to a PostgreSQL database, as I mentioned in https://github.com/pydanny/cookiecutter-django/issues/1541#issuecomment-500194456:

```python
DATABASES = {
    'default': env.db('DATABASE_URL', default='postgres:///{{cookiecutter.project_slug}}'),
```
Therefore the related test database backend is automatically inherited from the default one and can't be anything else (e.g. SQLite).

Besides, if you don't explicitly enable PostgreSQL server in Travis CI build environment the builds will always fail because all the connection attempts to PostgreSQL database fail. (`psycopg2.OperationalIssue`).

**Comment by nmago** [comment]
Hi!
Here is a project-local solution: add
`DATABASE_URL=postgresql://localhost/{{cookiecutter.project_slug}} `
as environment variable in Travis repo settings.

**Comment by Datamance** [comment]
> Are you sure pytest creates psql databases? Maybe it just falls back to sqlite?

@step21 did you ever get an answer to this?

**Comment by step21** [comment]
> > Are you sure pytest creates psql databases? Maybe it just falls back to sqlite?
> 
> @step21 did you ever get an answer to this?

No, sorry.

**Comment by wandering-tales** [comment]
@Datamance I replied to @step21 question in https://github.com/pydanny/cookiecutter-django/issues/2100#issuecomment-507078188.
