### ISSUE TITLE
Fresh app fail -  'str' object is not callable & testrunner

### ISSUE THREAD

**Issue by ad-m** [pydanny/cookiecutter-django#223]
```bash
(etr)adas@adas-AMILO-Pro-V3205:/tmp/cookie/test_project$ export DJANGO_SECRET_KEY=`random_pass`
(etr)adas@adas-AMILO-Pro-V3205:/tmp/cookie/test_project$ python test_project/manage.py migrate
Traceback (most recent call last):
  File "test_project/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/tmp/etr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/tmp/etr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/tmp/etr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/tmp/etr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/tmp/etr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/cookie/test_project/test_project/config/local.py", line 21, in <module>
    SECRET_KEY = env("DJANGO_SECRET_KEY", 'CHANGEME!!!')
  File "/tmp/etr/local/lib/python2.7/site-packages/environ/environ.py", line 117, in __call__
    return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
  File "/tmp/etr/local/lib/python2.7/site-packages/environ/environ.py", line 260, in get_value
    value = self.parse_value(value, cast)
  File "/tmp/etr/local/lib/python2.7/site-packages/environ/environ.py", line 308, in parse_value
    value = cast(value)
TypeError: 'str' object is not callable
```
Some workaround is:
```diff
diff --git a/test_project/config/local.py b/test_project/config/local.py
index 2918431..eaac4e5 100644
- a/test_project/config/local.py
+ b/test_project/config/local.py
@@ -18,7 +18,7 @@ TEMPLATE_DEBUG = DEBUG
 # ------------------------------------------------------------------------------
 # See: https://docs.djangoproject.com/en/dev/ref/settings/#secret-key
 # Note: This key only used for development and testing.
-SECRET_KEY = env("DJANGO_SECRET_KEY", 'CHANGEME!!!')
+SECRET_KEY = env("DJANGO_SECRET_KEY")
 
 # Mail settings
 # ------------------------------------------------------------------------------
```

After that we have still warning in any manage.py command:

```
WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
```

We can fix that by:
```diff
diff --git a/test_project/config/common.py b/test_project/config/common.py
index 9c68a1b..7db6260 100644
--- a/test_project/config/common.py
+++ b/test_project/config/common.py
@@ -257,5 +257,5 @@ LOGGING = {
         },
     }
 }
-
-# Your common stuff: Below this line define 3rd party library settings
\ No newline at end of file
+TEST_RUNNER = 'django.test.runner.DiscoverRunner'
+# Your common stuff: Below this line define 3rd party library settings
```

**Comment by theskumar** [comment]
Thanks for reporting this! Added fixes in https://github.com/pydanny/cookiecutter-django/commit/47f89d9df1b4cf44fee0017a84a6ad44b5e74870

SECRET_KEY should have been 
```
SECRET_KEY= env("DJANGO_SECRET", default="CHANGE_ME!!")
```
