### ISSUE TITLE
#deploying on EC2 AWS ubnutu - ModuleNotFoundError: No module named 'debug_toolbar'

### ISSUE THREAD

**Issue by m7salam** [pydanny/cookiecutter-django#2296]
## What happened?
tried to collect static 

python manage.py collectstatic 

and then comes this error

Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/goPiamo-track/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/goPiamo-track/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/ubuntu/goPiamo-track/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/goPiamo-track/venv/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/goPiamo-track/venv/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/ubuntu/goPiamo-track/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'debug_toolbar'

tried adding 

export DJANGO_SETTINGS_MODULE='config.settings.production'

to my env file and also doesn't work ?!

any solution or anything im missing ?

**Comment by m7salam** [comment]
figured it out , just needed to change the manage,py instead of .local to .production 

so that's why im closing this issue now :)
