### ISSUE TITLE
White Noise Can't be found

### ISSUE THREAD

**Issue by acquayefrank** [pydanny/cookiecutter-django#230]
The WhiteNoise Library has been placed under production.txt hence it's not installed in the development environment- although  it's being called in the wsgi.py. This leads to an error when the runserver command is used. I'm assuming I'm supposed to set something in my environment for this to work??

**Comment by theskumar** [comment]
@acquayefrank If you use `python manage.py runserver`, it should be referencing the `wsgi.py`. `wsgi.py` is used only in production, if you are testing your wsgi.py in development, yes you'll need to install whitenoise on your local machine.

Let me know, if that answers your question.

**Comment by acquayefrank** [comment]
Below is the stack trace I get when I run  python manage.py runserver:

Django version 1.8, using settings 'config.settings.local'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0xb5ccd144>
Traceback (most recent call last):
  File "/home/larry/Documents/Projects/witaji/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 223, in wrapper
    fn(*args, **kwargs)
  File "/home/larry/Documents/Projects/witaji/env/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/larry/Documents/Projects/witaji/env/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 24, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/larry/Documents/Projects/witaji/env/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 55, in get_handler
    return get_internal_wsgi_application()
  File "/home/larry/Documents/Projects/witaji/env/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 60, in get_internal_wsgi_application
    sys.exc_info()[2])
  File "/home/larry/Documents/Projects/witaji/env/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 50, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/larry/Documents/Projects/witaji/env/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/larry/Documents/Projects/witaji/witaji/config/wsgi.py", line 19, in <module>
    from whitenoise.django import DjangoWhiteNoise
django.core.exceptions.ImproperlyConfigured: WSGI application 'config.wsgi.application' could not be loaded; Error importing module: 'No module named whitenoise.django'

**Comment by pydanny** [comment]
I wonder if it is caused by https://github.com/pydanny/cookiecutter-django/blob/8bfe28a72107a228ef1ee050aa83fcd07281b924/%7B%7Bcookiecutter.repo_name%7D%7D/config/settings/common.py#L195. 

Once I get a certain book out today, I'll try to resolve this.

**Comment by theskumar** [comment]
I tried in a fresh virtualenv and everything seems to work fine. Including `manage.py migrate` and `manage.py test` but not the `manage.py runserver` I've moved the whitenoise requirement to `base.txt`. That should resolve the issue. 

Thanks a lot @acquayefrank for reporting this! :)
