### ISSUE TITLE
HStoreExtension is missin in 0001_initial.py

### ISSUE THREAD

**Issue by siless** [pydanny/cookiecutter-django#2604]
## What happened?
If you use the postgresql specific model field HStoreField() after creating a 0001_initial.py file does not contain the HStoreExtension() for migration.

## What should've happened instead?
If you use HStoreField(), the 0001_initial.py has to contain the HStoreExtions() in operations[HStoreExtension(), migration.CreateModel.....]

## Steps to reproduce
- create a model with postgres field like "param =  django.contrib.prostgres.fields.HStoreField()"
- run makemigration
- run migrate to create a 0001_initial.py

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
- Ubuntu 18.04
- docker client community 19.03.8
- docker engine community 19.03.8
- docker compose 1.25.5
- docker-py 4.1.0
- cpython 3.7.5
- pycharm prof 2020.1 build 30 April 2020 
- cookiecutter  Latest commit 606b4c5 May 13, 2020
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by siless** [comment]
Terminal output after running migrate:

(venv)$ docker-compose -f local.yml run --rm django python manage.py migrate reporter
Starting postgres ... done
PostgreSQL is available
Operations to perform:
  Apply all migrations: reporter
Running migrations:
  Applying reporter.0001_initial...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedObject: type "hstore" does not exist
LINE 1: ...e" varchar(100) NOT NULL, "environment_variables" hstore NOT...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 324, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: type "hstore" does not exist
LINE 1: ...e" varchar(100) NOT NULL, "environment_variables" hstore NOT...

**Comment by foarsitter** [comment]
The django docs are clear about [this]:(https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/fields/#django.contrib.postgres.fields.HStoreField): 

1. Add 'django.contrib.postgres' in your INSTALLED_APPS.
2. Setup the hstore extension in PostgreSQL.

So it is your own responsibility to create the migration containing the HStoreExtension.

**Comment by siless** [comment]
I tried the approach like foarsitter and django docs said. It did not work. 
It is necessary to add HStoreExtension() to 0001_inital.py

`operations = [
        HStoreExtension(),
        migrations.CreateModel(`
