### ISSUE TITLE
Getting an error on project generation

### ISSUE THREAD

**Issue by mindcube** [pydanny/cookiecutter-django#275]
Traceback (most recent call last):
  File "/home/vagrant/ilikealice/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/cookiecutter/cli.py", line 70, in main
    cookiecutter(template, checkout, no_input)
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/cookiecutter/main.py", line 102, in cookiecutter
    context=context
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 204, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 114, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/home/vagrant/ilikealice/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "./{{cookiecutter.repo_name}}/templates/users/user_list.html", line 2, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'load'.
  File "./{{cookiecutter.repo_name}}/templates/users/user_list.html", line 2
    {% load static %}{% load i18n %}

**Comment by luzfcb** [comment]
fixed in #276 

plz try again. :+1:

**Comment by mindcube** [comment]
Thank you!  All is well.
