### ISSUE TITLE
NodeNotFoundError

### ISSUE THREAD

**Issue by julialoh** [pydanny/cookiecutter-django#2769]
## What happened?
I'm trying to develop locally and have run into an error when I run the local.yml up command. 

## What should've happened instead?
Django shouldn't have exited and I should have been able to develop locally on the docker.

## Steps to reproduce
I get this error: 
```django          | Traceback (most recent call last):
django          |   File "manage.py", line 31, in <module>
django          |     execute_from_command_line(sys.argv)
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
django          |     utility.execute()
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
django          |     self.fetch_command(subcommand).run_from_argv(self.argv)
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
django          |     self.execute(*args, **cmd_options)
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
django          |     output = self.handle(*args, **options)
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
django          |     res = handle_func(*args, **kwargs)
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 86, in handle
django          |     executor = MigrationExecutor(connection, self.migration_progress_callback)
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
django          |     self.loader = MigrationLoader(self.connection)
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
django          |     self.build_graph()
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 274, in build_graph
django          |     raise exc
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 248, in build_graph
django          |     self.graph.validate_consistency()
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
django          |     [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
django          |     [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/graph.py", line 58, in raise_error
django          |     raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django          | django.db.migrations.exceptions.NodeNotFoundError: Migration reservations.0001_initial dependencies reference nonexistent parent node ('river', '0002_auto_20200805_1323')
celeryworker    | [2020-08-26 15:46:04,489: INFO/MainProcess] Connected to redis://redis:6379/0
celeryworker    | [2020-08-26 15:46:04,505: INFO/MainProcess] mingle: searching for neighbors
django exited with code 1
``` 

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by browniebroke** [comment]
Looks like you have 2 DB migrations that have a broken dependency:

`Migration reservations.0001_initial dependencies reference nonexistent parent node ('river', '0002_auto_20200805_1323')`

These come from 2 separate Django apps, `reservations` and `river`, none of which are included in the project template. This is likely not a bug with Cookiecutter Django. Please can you reach out to more appropriate support channels before opening issues here? 

This project is supported by unpaid volunteers, I'm happy to get real issues reported, but this is not the case here.
