### ISSUE TITLE
Latest Version of django-timezone-field breaks all new Celery-based Projects

### ISSUE THREAD

**Issue by omarsumadi** [pydanny/cookiecutter-django#2950]
## What happened?
When creating a new cookie-cutter project using cookiecutter-django:
1) pip install "cookiecutter>=1.7.0"
2) cookiecutter https://github.com/pydanny/cookiecutter-django
3) Choose Celery
4) docker-compose -f local.yml run --rm django python manage.py migrate

django-celery-beat migration named 0013_auto_20200609_0727.py will fail, giving an error trace of:
```
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 566, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 152, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 681, in _alter_field
    new_default = self.effective_default(new_field)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 303, in effective_default
    return field.get_db_prep_save(self._effective_default(field), self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 282, in _effective_default
    default = field.get_default()
  File "/usr/local/lib/python3.8/site-packages/timezone_field/fields.py", line 114, in get_default
    value = super(TimeZoneField, self).get_default()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 829, in get_default
    return self._get_default()
  File "/usr/local/lib/python3.8/site-packages/django_celery_beat/models.py", line 60, in crontab_schedule_celery_timezone
    choice[0].zone for choice in timezone_field.TimeZoneField.CHOICES
AttributeError: type object 'TimeZoneField' has no attribute 'CHOICES'
```
## What should've happened instead?
- Migration should succeed.

## Fix
In base.txt for requirement, mandate:
django-timezone-field==4.0

## Reason:
django-celery-beat setup.py has a requirements file of https://github.com/celery/django-celery-beat/blob/master/requirements/default.txt, mandating: django-timezone-field>=4.0,<5.0. The owner recently pushed django-timezone-field version 4.1.1, which broke that migration.

Version 4.0 works though.

**Comment by davidrothera** [comment]
https://github.com/celery/django-celery-beat/pull/378 fixes the breakage, for now though pinning it as listed above is the easiest fix :)

**Comment by Andrew-Chen-Wang** [comment]
Seems to be a quick patch release though, so not sure if timezone package needs to be pinned?

**Comment by browniebroke** [comment]
It all depends how quickly the fix in `django-celery-beat` will be released. Someone just rightly commented that the current fix breaks compatibility with 4.0 and earlier.

We can wait a couple of days, hopefully it will be quick, yes.

**Comment by joshlsullivan** [comment]
@omarsumadi where exactly do I change the version?

**Comment by omarsumadi** [comment]
@joshlsullivan The project mainters did it for you, check it out here: https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/base.txt

They added the line:
django-timezone-field==4.0  # https://github.com/celery/django-celery-beat/pull/378

So that when your project is built, it defines the version for django-timezone-field
Then when celery/celerybeat is installed, it notices that django-timezone-field is already installed and says, ok, don't install the incorrect version since you specified the correct version already

**Comment by joshlsullivan** [comment]
> @joshlsullivan The project mainters did it for you, check it out here: https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/base.txt
> 
> They added the line:
> django-timezone-field==4.0 # [celery/django-celery-beat#378](https://github.com/celery/django-celery-beat/pull/378)
> 
> So that when your project is built, it defines the version for django-timezone-field
> Then when celery/celerybeat is installed, it notices that django-timezone-field is already installed and says, ok, don't install the incorrect version since you specified the correct version already

Interval is working for me, but crontab is displaying that error. Added Celery Beat to a project last night.

**Comment by omarsumadi** [comment]
@joshlsullivan Can you post the full error trace?

**Comment by joshlsullivan** [comment]
> @joshlsullivan Can you post the full error trace?

`Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1594, in _changeform_view
    form = ModelForm(initial=initial)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/forms/models.py", line 290, in __init__
    self.instance = opts.model()
  File "/app/.heroku/python/lib/python3.8/site-packages/django/db/models/base.py", line 475, in __init__
    val = field.get_default()
  File "/app/.heroku/python/lib/python3.8/site-packages/timezone_field/fields.py", line 114, in get_default
    value = super(TimeZoneField, self).get_default()
  File "/app/.heroku/python/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 831, in get_default
    return self._get_default()
  File "/app/.heroku/python/lib/python3.8/site-packages/django_celery_beat/models.py", line 60, in crontab_schedule_celery_timezone
    choice[0].zone for choice in timezone_field.TimeZoneField.CHOICES

Exception Type: AttributeError at /admin/django_celery_beat/crontabschedule/add/
Exception Value: type object 'TimeZoneField' has no attribute 'CHOICES'
`

**Comment by omarsumadi** [comment]
@joshlsullivan Can you check what version of Django Timezone Field you are using and tell me? Maybe they fixed something in later versions and we should have informed the project maintainers to update the package to the latest django-timezone-field version.

Check this out:
https://github.com/celery/django-celery-beat/commits/master
