### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by yswtrue** [pydanny/cookiecutter-django#3004]
## What happened?

`make -C docs livehtml`

## Additional details

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): Cookiecutter 1.7.2
    * OS:macos 
    * Python version:3.8.2
    * Docker versions (if using Docker):
    * ...
   
<summary>
Logs:
<details>
<pre>
sphinx-autobuild -b html --host 0.0.0.0 --port 7000 --watch /app -c . . ./_build/html
+--------------------------------- manual build ---------------------------------
| 正在运行 Sphinx v3.4.2

Configuration error:
配置文件中有程序上的错误：

Traceback (most recent call last):
  File "/Users/yswtrue/Code/lion_backend/.venv/lib/python3.8/site-packages/sphinx/config.py", line 326, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/yswtrue/Code/lion_backend/.venv/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/Users/yswtrue/Code/lion_backend/docs/conf.py", line 26, in <module>
    django.setup()
  File "/Users/yswtrue/Code/lion_backend/.venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/yswtrue/Code/lion_backend/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/Users/yswtrue/Code/lion_backend/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/yswtrue/Code/lion_backend/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/yswtrue/.pyenv/versions/3.8.2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'

+--------------------------------------------------------------------------------
[I 210112 23:35:26 server:335] Serving on http://0.0.0.0:7000
[I 210112 23:35:26 handlers:62] Start watching changes
[I 210112 23:35:26 handlers:64] Start detecting changes
</pre>
</details>
</summary>

**Comment by binaryeast** [comment]
Hello, Please read [this issue first](https://github.com/pydanny/cookiecutter-django/issues/1725).

Maybe your apps' path aren't located in <project_slug> directory.


First, move your app folders into the <project_slug> directory.

And try again. If it doesn't work,

Second, add this code in docs/conf.py under the **sys.path.insert() function** line.

If you running locally with docker:
 
```python
sys.path.append(os.path.abspath("/app/<project_slug>"))
```

Maybe line 25.

else:

```python
sys.path.append(os.path.abspath("../../"))
```

Maybe line 19.

I will cross the finger for you.

**Comment by browniebroke** [comment]
I'm closing this issue as I'm assuming the original issue was solved. Feel free to reopen with more details if the problem persists.

**Comment by ghftw** [comment]
I encountered the same problem. The suggestion worked for me, but with only one parent directory appended before the if else:

sys.path.append(os.path.abspath("../"))
