### ISSUE TITLE
TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>

### ISSUE THREAD

**Issue by lionelyoung** [pydanny/cookiecutter-django#3253]
## What happened?

TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>

## What should've happened instead?

No error

## Additional details

Might be a version mismatch for Twisted, since I added channels

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`):
    * OS name and version:

        ```bash
              # Insert here the OS name and version
              Distributor ID: Ubuntu
        Description:    Ubuntu 20.04.2 LTS
        Release:        20.04
        Codename:       focal
        ```

    * Python version, run `python3 -V`: Python 3.8.10
    * Docker version (if using Docker), run `docker --version`: Docker version 20.10.6, build 370c289
    * docker-compose version (if using Docker), run `docker-compose --version`: docker-compose version 1.27.4, build 40524192

* Options selected
```json
{
  "cookiecutter": {
    "project_name": "My Awesome Project",
    "project_slug": "x",
    "description": "x",
    "author_name": "x",
    "domain_name": "x.x.x",
    "email": "x@example.com",
    "version": "0.1.0",
    "open_source_license": "Not open source",
    "timezone": "UTC",
    "windows": "n",
    "use_pycharm": "n",
    "use_docker": "y",
    "postgresql_version": "13.2",
    "js_task_runner": "None",
    "cloud_provider": "None",
    "mail_service": "Other SMTP",
    "use_async": "y",
    "use_drf": "y",
    "custom_bootstrap_compilation": "n",
    "use_compressor": "n",
    "use_celery": "n",
    "use_mailhog": "n",
    "use_sentry": "n",
    "use_whitenoise": "y",
    "use_heroku": "n",
    "ci_tool": "None",
    "keep_local_envs_in_vcs": "y",
    "debug": "n",
    "_template": "https://github.com/pydanny/cookiecutter-django"
  }
}
```
<summary>
Logs:
<details>
<pre>
django      | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
django      | INFO:     Started reloader process [10] using watchgod
django      | Process SpawnProcess-1:
django      | Traceback (most recent call last):
django      |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
django      |     self.run()
django      |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
django      |     self._target(*self._args, **self._kwargs)
django      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
django      |     target(sockets=sockets)
django      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 50, in run
django      |     loop.run_until_complete(self.serve(sockets=sockets))
django      |   File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
django      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 57, in serve
django      |     config.load()
django      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 318, in load
django      |     self.loaded_app = import_from_string(self.app)
django      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 22, in import_from_string
django      |     module = importlib.import_module(module_str)
django      |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
django      |     return _bootstrap._gcd_import(name[level:], package, level)
django      |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
django      |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
django      |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
django      |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
django      |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
django      |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
django      |   File "/app/./config/asgi.py", line 25, in <module>
django      |     django_application = get_asgi_application()
django      |   File "/usr/local/lib/python3.9/site-packages/django/core/asgi.py", line 12, in get_asgi_application
django      |     django.setup(set_prefix=False)
django      |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
django      |     apps.populate(settings.INSTALLED_APPS)
django      |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
django      |     app_config = AppConfig.create(entry)
django      |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 116, in create
django      |     mod = import_module(mod_path)
django      |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
django      |     return _bootstrap._gcd_import(name[level:], package, level)
django      |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
django      |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
django      |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
django      |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
django      |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
django      |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
django      |   File "/usr/local/lib/python3.9/site-packages/channels/apps.py", line 4, in <module>
django      |     import daphne.server
django      |   File "/usr/local/lib/python3.9/site-packages/daphne/server.py", line 20, in <module>
django      |     asyncioreactor.install(twisted_loop)
django      |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/asyncioreactor.py", line 307, in install
django      |     reactor = AsyncioSelectorReactor(eventloop)
django      |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/asyncioreactor.py", line 60, in __init__
django      |     raise TypeError(
django      | TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>
</pre>
</details>
</summary>

**Comment by lionelyoung** [comment]
Locking twisted to Twisted==20.3.0 fixes this

**Comment by lionelyoung** [comment]
Closing, because this is a channels issue
