### ISSUE TITLE
did not locate library pango-1.0-0

### ISSUE THREAD

**Issue by aabanaag** [pydanny/cookiecutter-django#3304]
## What happened?
I was using the WeasyPrint module, I had to update the docker file and include the library dependencies and was working perfectly but all of a sudden last Friday the build was failing and I can't seem to run my project locally due to the issue `OSError: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'`

## What should've happened instead?
It should run the project without issues, It should render the HTML templates to PDF using weasyprint

## Additional details

I did not configured the project, so I don't have cookie-cutter installed locally before.

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): 
    * OS name and version: MacOS 11.4

      On Linux, run 
      ```bash
      lsb_release -a 2> /dev/null || cat /etc/redhat-release 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null
      ```

      On MacOs, run
      ```bash
      sw_vers
      ```
      
      On Windows, via CMD, run
      ```
      systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      ```

      ```bash
      # Insert here the OS name and version
      
      ```

    * Python version, run `python3 -V`: 3.8.9
    * Docker version (if using Docker), run `docker --version`: 3.5.2
    * docker-compose version (if using Docker), run `docker-compose --version`: 2.0.0-beta-6
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and MacOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)

  Again, I did not configure the project I don't have cookie-cutter installed but I'm using docker as one of the options

    ```json
    # Insert here the replay file content
    ```
<summary>
Logs:
<details>
<pre>
PostgreSQL is available
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/water_conservation_api/core/admin.py", line 16, in <module>
    from water_conservation_api.core.services import OrganizationService
  File "/app/water_conservation_api/core/services.py", line 19, in <module>
    from water_conservation_api.core.tasks import generate_mailer, import_water_bill_records
  File "/app/water_conservation_api/core/tasks.py", line 10, in <module>
    from water_conservation_api.utils.helpers import generate_pdf, send_job_notification
  File "/app/water_conservation_api/utils/helpers.py", line 9, in <module>
    from weasyprint import HTML
  File "/usr/local/lib/python3.8/site-packages/weasyprint/__init__.py", line 322, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/usr/local/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/usr/local/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 16, in <module>
    from ..text.ffi import ffi, pango, units_to_double

  File "/usr/local/lib/python3.8/site-packages/weasyprint/text/ffi.py", line 383, in <module>
    pango = _dlopen(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/text/ffi.py", line 377, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'

</pre>
</details>
</summary>

**Comment by luzfcb** [comment]
@aabanaag 

Are you sure to install all WeasyPrint Debian dependencies on the build and run stages of the docker? 
This project uses the docker multi-stage builds:
 https://docs.docker.com/develop/develop-images/multistage-build/
 


https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#debian-11

```
python3-pip python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0
```

You must repeat dependencies after these two lines.

https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/Dockerfile#L14

https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/Dockerfile#L41



And then rebuild everything ignoring the build cache

```
docker-compose -f local.yml build --no-cache
```

**Comment by aabanaag** [comment]
I did installed it on both build and run stages..

**Comment by aabanaag** [comment]
hmm.. is there any reason why it needs to be after those lines?

**Comment by aabanaag** [comment]
my bad, turns out I need to also add the dependencies on the docs dockerfile. Thank you
