### ISSUE TITLE
coverage + celery taskapp + testing = ??

### ISSUE THREAD

**Issue by alexkahn** [pydanny/cookiecutter-django#343]
Interesting issue:

I've done a little customization (but nothing crazy) on a basic cookiecutter-django installation.

When I run the normal ```./manage.py test```, everything is fine.

BUT if I do something like:

```coverage run manage.py test```

I get:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/path/to/my/project/project/taskapp/celery.py", line 4, in <module>
    from celery import Celery
ImportError: No module named celery
```

Context:
OSX Yosemite
Python 2.7.10

pip freeze:
```
alabaster==0.7.6
amqp==1.4.6
anyjson==0.3.3
appnope==0.1.0
Babel==2.0
billiard==3.3.0.20
celery==3.1.18
coverage==3.7.1
decorator==4.0.2
Django==1.8.4
django-allauth==0.23.0
django-autoslug==1.8.0
django-braces==1.8.1
django-crispy-forms==1.5.2
django-debug-toolbar==1.3.2
django-environ==0.3.0
django-extensions==1.5.6
django-floppyforms==1.5.2
django-model-utils==2.3.1
django-redis==4.2.0
django-secure==1.0.1
django-test-plus==1.0.9
docutils==0.12
factory-boy==2.5.2
gnureadline==6.3.3
greenlet==0.4.9
ipdb==0.8.1
ipython==4.0.0
ipython-genutils==0.1.0
Jinja2==2.8
kombu==3.0.26
MarkupSafe==0.23
msgpack-python==0.4.6
oauthlib==1.0.3
path.py==8.1.1
pexpect==3.3
pickleshare==0.5
Pillow==2.9.0
psycopg2==2.6.1
Pygments==2.0.2
python-openid==2.2.5
pytz==2015.4
redis==2.10.3
requests==2.7.0
requests-oauthlib==0.5.0
simplegeneric==0.8.1
six==1.9.0
snowballstemmer==1.2.0
Sphinx==1.3.1
sphinx-rtd-theme==0.1.9
sqlparse==0.1.16
traitlets==4.0.0
unicode-slugify==0.1.3
Unidecode==0.4.18
Werkzeug==0.10.4
wheel==0.24.0
```

Let me know if you need some additional information!

Thanks!

**Comment by andresgz** [comment]
I have tested in my test project and coverage test works with no problem.
![image](https://cloud.githubusercontent.com/assets/1609644/10115581/26f778ba-63d2-11e5-97da-f1ea28594402.png)

Your error seems related to celery, make sure you are running in the right environment, and that environment has installed celery.
Try to install it before running the coverage test: 

    celery==3.1.18

**Comment by alexkahn** [comment]
Thanks for the reply, Celery is installed in my virtual environment. The pip freeze I offered above does include it, although it is quite a large list of packages. Do you have Celery running in a different terminal or as a background process when you run your tests with coverage?

**Comment by pydanny** [comment]
I can't replicate this problem so I'm closing it. If it is still a problem, please reopen.
