### ISSUE TITLE
Can't get my django app running with gunicorn on production server

### ISSUE THREAD

**Issue by d3prof3t** [pydanny/cookiecutter-django#384]
My config/wsgi file -> https://dpaste.de/buFf
Then I run 'gunicorn config.wsgi' and it the following error.
Error Log:-> https://dpaste.de/DFay

**Comment by jayfk** [comment]
Are you importing something in your settings files?

**Comment by d3prof3t** [comment]
in the common.py?

**Comment by jayfk** [comment]
Yeah, or in `production.py`

**Comment by d3prof3t** [comment]
production.py is untouched.
My common.py : https://dpaste.de/GBNc

**Comment by jayfk** [comment]
Okay, that was just a quick guess. These errors often come up when importing Django modules when the settings are not *ready* yet.

**Comment by d3prof3t** [comment]
hmm, so what is the issue cozm I even tried setting the DJANGO_SETTINGS_MODULE before importing whinoise in wsgi.py,(although its pep8 violation) but still ws trying it out.
And it gave me the follwing error: https://dpaste.de/j0ZP

**Comment by d3prof3t** [comment]
What's the workaround to this?

**Comment by luzfcb** [comment]
@d3prof3t please, try define DJANGO_SECRET_KEY environment variable

Open terminal, load the virtualenv of your project and run:

```bash
export DJANGO_SECRET_KEY=yourandomsecretkey
python manage.py runserver -v 3
```

and send output to here

**Comment by d3prof3t** [comment]
@luzfcb It is giving me the normal output

Performing system checks...

System check identified no issues (0 silenced).
October 22, 2015 - 17:03:32
Django version 1.8.5, using settings 'config.settings.local'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

**Comment by luzfcb** [comment]
try again with the production settings on you production server:

```
export DJANGO_SECRET_KEY=yourandomsecretkey
python manage.py runserver -v 3 --settings config.settings.production 0.0.0.0:8004
```
and send output to here.

**Comment by d3prof3t** [comment]
Traceback (most recent call last):
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/environ/environ.py", line 249, in get_value
    value = os.environ[var]
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib64/python3.4/os.py", line 633, in __getitem__
    raise KeyError(key) from None
KeyError: 'DJANGO_AWS_ACCESS_KEY_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 14, in <module>
    from django.db.migrations.executor import MigrationExecutor
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/db/migrations/executor.py", line 6, in <module>
    from .loader import MigrationLoader
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/db/migrations/loader.py", line 10, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 9, in <module>
    class MigrationRecorder(object):
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 23, in MigrationRecorder
    class Migration(models.Model):
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 24, in Migration
    app = models.CharField(max_length=255)
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 1081, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 161, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/saurabh/Projects/python/django-projects/cricket_fantasy_project/config/settings/production.py", line 72, in <module>
    AWS_ACCESS_KEY_ID = env('DJANGO_AWS_ACCESS_KEY_ID')
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/environ/environ.py", line 111, in __call__
    return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
  File "/home/saurabh/.virtualenvs/cricketFantasy/lib/python3.4/site-packages/environ/environ.py", line 253, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the DJANGO_AWS_ACCESS_KEY_ID environment variable

**Comment by Eraldo** [comment]
Seems like you enabled amazon s3 support.
In this case you also need to set 'DJANGO_AWS_ACCESS_KEY_ID' just like you
did with 'DJANGO_SECRET_KEY'.
(along with the other setup options for amazon aws)

\o/,
Eraldo

-- 
/============================================
| *E r a l d o    E n e r g y*
| *Coach*: Personal Development
| *Dancer*: Salsa, Bachata, Kizomba & Co.
| *Developer*: Python/Django
| *Legend*: CoLegend.org <http://www.colegend.org>
|--------------------------------------------
| M: +49 176 97 99 44 80 <004917697994480>
| E: eraldo@eraldo.org
| W: www.eraldo.org
| S: www.facebook.com/Eraldo
\============================================
Be Awesome! Love with an Open Heart! And Live a Legendary Life.. Today!

**Comment by d3prof3t** [comment]
@Eraldo 
Actually I didn't enable anything on my own.
But anyways, if I want to disable that. How to go about that?

**Comment by d3prof3t** [comment]
Okkay, so I have commented out all the AWS settings in production.py

**Comment by Eraldo** [comment]
You are right.. it is the default storage:
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
Set:
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
To get back to django's default storage.

\o/,
Eraldo

-- 
/============================================
| *E r a l d o    E n e r g y*
| *Coach*: Personal Development
| *Dancer*: Salsa, Bachata, Kizomba & Co.
| *Developer*: Python/Django
| *Legend*: CoLegend.org <http://www.colegend.org>
|--------------------------------------------
| M: +49 176 97 99 44 80 <004917697994480>
| E: eraldo@eraldo.org
| W: www.eraldo.org
| S: www.facebook.com/Eraldo
\============================================
Be Awesome! Love with an Open Heart! And Live a Legendary Life.. Today!

**Comment by Eraldo** [comment]
Yeah.. or comment it out to get back to the default.. I guess that makes
even more sense. ;)

\o/,
Eraldo

-- 
/============================================
| *E r a l d o    E n e r g y*
| *Coach*: Personal Development
| *Dancer*: Salsa, Bachata, Kizomba & Co.
| *Developer*: Python/Django
| *Legend*: CoLegend.org <http://www.colegend.org>
|--------------------------------------------
| M: +49 176 97 99 44 80 <004917697994480>
| E: eraldo@eraldo.org
| W: www.eraldo.org
| S: www.facebook.com/Eraldo
\============================================
Be Awesome! Love with an Open Heart! And Live a Legendary Life.. Today!

**Comment by d3prof3t** [comment]
@Eraldo 
I am actually using digital ocean not AWS.

And just have a look at this, I've commented out almost all the environment variables, because its giving me errors on almost all the environment variables.
Now I want to know how to get my settings of local.py such as my database server  and all running without debug mode.
production.py: -> https://dpaste.de/BfWR

**Comment by Eraldo** [comment]
Sorry.. I do not have time took at this any further right now. :|

\o/,
Eraldo

-- 
/============================================
| *E r a l d o    E n e r g y*
| *Coach*: Personal Development
| *Dancer*: Salsa, Bachata, Kizomba & Co.
| *Developer*: Python/Django
| *Legend*: CoLegend.org <http://www.colegend.org>
|--------------------------------------------
| M: +49 176 97 99 44 80 <004917697994480>
| E: eraldo@eraldo.org
| W: www.eraldo.org
| S: www.facebook.com/Eraldo
\============================================
Be Awesome! Love with an Open Heart! And Live a Legendary Life.. Today!

**Comment by d3prof3t** [comment]
Can anyone else look at this?

**Comment by luzfcb** [comment]
please, make sure you have set all environment variables defined in http://cookiecutter-django.readthedocs.org/en/latest/settings.html

and try comment the CACHE section in you production settings https://dpaste.de/BfWR

**Comment by d3prof3t** [comment]
@luzfcb Hi!
I saw that link in the doc u suggested. Actually I have never dealt with environmnet variables. Can you provide a bit more detail with setting up a single sample environment variable and how to map it in the production.py ?

**Comment by d3prof3t** [comment]
Like for instance I had to do a export my DJANGO_SECRET_KEY before running the server with production settings. How can I go about that doing it in the production.py

**Comment by luzfcb** [comment]
`cookiecutter-django` officially, only supports deploy in Heroku and/or Docker, but, however, the generated project works almost without any modification in Digital Ocean.

If you want to submit a pull-request with documentation on how to deploy `cookiecutter-django` based project on DigitalOcean it would be good because it would help other people with the same necessity.

due to not being a problem with cookiecutter-django, but with the understanding of how to deploy a Django application, I will close this

**Comment by luzfcb** [comment]
cookiecutter-django uses some of the ideas http://12factor.net/

I recommend you read:

https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-django-with-postgres-nginx-and-gunicorn

**Comment by luzfcb** [comment]
you can create environment variables simply by using the `export` command

```bash
export MYVAR=value
```

to show

```bash
echo $MYVAR
```

**Comment by d3prof3t** [comment]
@luzfcb 
Thanks a lot!
I'll try and implement all this. And as soon as I get it deployed successfully, I'll surely submit a pull request.
Cheers!
