### ISSUE TITLE
docker-docker-compose migrate gets BadMigrationError

### ISSUE THREAD

**Issue by garrypolley** [pydanny/cookiecutter-django#400]
Currently using Django `1.8.6 ` the command recommended to migrate the database fails to run. 

Command: `docker-compose run django python manage.py migrate`

Error: 

```sh
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.load_disk()
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 123, in load_disk
    "creating Django migrations." % app_config.label
django.db.migrations.loader.BadMigrationError: Migrated app 'django_extensions' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.
```

I'm not sure what is causing the error but when using `1.8.5` the error does not happen. Likely this is a Django issue but I wanted to log it here since the error occurred while I was following the doc to setup a new site.

**Comment by luzfcb** [comment]
Try update django-extension to latest version.

If solve the problem, close this issue.
Em 08/11/2015 14:20, "Garry Polley" <notifications@github.com> escreveu:
