### ISSUE TITLE
cookiecutter fails on jinja2.exceptions.TemplateSyntaxError

### ISSUE THREAD

**Issue by patvdleer** [pydanny/cookiecutter-django#528]
~~~
timezone [UTC]:     
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/cookiecutter/cli.py", line 100, in main
    config_file=user_config
  File "/usr/local/lib/python3.4/dist-packages/cookiecutter/main.py", line 131, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/usr/local/lib/python3.4/dist-packages/cookiecutter/prompt.py", line 126, in prompt_for_config
    val = render_variable(env, raw, cookiecutter_dict)
  File "/usr/local/lib/python3.4/dist-packages/cookiecutter/prompt.py", line 86, in render_variable
    template = env.from_string(raw)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 470, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 897, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 879, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 135, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 88, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 81, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/parser.py", line 50, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'now'.
~~~

~~~
sudo -H pip3 install -U django jinja2
Requirement already up-to-date: django in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: jinja2 in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: MarkupSafe in /usr/local/lib/python3.4/dist-packages (from jinja2)
~~~

**Comment by luzfcb** [comment]
please, update the cookiecutter to version 1.4.0 and try again. if that resolves the problem, please close this issue.


```bash
pip install cookiecutter --upgrade
```

This project now requires cookiecutter version> = 1.4


This problem occurred because of this commit: https://github.com/pydanny/cookiecutter-django/commit/f4cf5df53e57acb338ee9c9aca24d58709dbcfb7


The cookiecutter> = 1.4, now includes by default the [jinja2-time](https://pypi.python.org/pypi/jinja2-time), an extension to Jinja2 to work with datetimes

before, the creation date of the project was defined by manual update the cookiecutter.json file, now the date is dynamically generated using jinja2-time .

**Comment by patvdleer** [comment]
Thanks! this fixes the issue!
