### ISSUE TITLE
setup with default settings fails

### ISSUE THREAD

**Issue by Eraldo** [pydanny/cookiecutter-django#546]
Python 3.5.1
Newest version: cookiecutter https://github.com/pydanny/cookiecutter-django fails.

Trace:
```
You've cloned /Users/eraldo/.cookiecutters/cookiecutter-django before. Is it okay to delete and re-clone it? [yes]: 
Cloning into 'cookiecutter-django'...
remote: Counting objects: 6038, done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 6038 (delta 26), reused 0 (delta 0), pack-reused 5973
Receiving objects: 100% (6038/6038), 2.55 MiB | 1.42 MiB/s, done.
Resolving deltas: 100% (3814/3814), done.
Checking connectivity... done.
project_name [project_name]: 
project_slug [project_name]: 
author_name [Your Name]: 
email [Your email]: 
description [A short description of the project.]: 
domain_name [example.com]: 
version [0.1.0]: 
timezone [UTC]: 
Traceback (most recent call last):
  File "/Users/eraldo/.virtualenvs/cookiecutter/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/cookiecutter/cli.py", line 100, in main
    config_file=user_config
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/cookiecutter/main.py", line 131, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/cookiecutter/prompt.py", line 126, in prompt_for_config
    val = render_variable(env, raw, cookiecutter_dict)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/cookiecutter/prompt.py", line 86, in render_variable
    template = env.from_string(raw)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/environment.py", line 470, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/parser.py", line 897, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/parser.py", line 879, in subparse
    rv = self.parse_statement()
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/parser.py", line 135, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/parser.py", line 88, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/parser.py", line 81, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/eraldo/.virtualenvs/cookiecutter/lib/python3.5/site-packages/jinja2/parser.py", line 50, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'now'.
```

I also tried with different name and timezone.. same error.
Any idea what is going on or how to fix it?

**Comment by luzfcb** [comment]
update the cookiecutter to version >= 1.4

pip3 install cookiecutter -U

or

sudo -H pip3 install cookiecutter -U

**Comment by jayfk** [comment]
see https://github.com/pydanny/cookiecutter-django/issues/528

**Comment by Eraldo** [comment]
Thanks that fixed it. :)
