### ISSUE TITLE
Webpack and Docker

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#637]
We should add instructions how to use them together **or** raise a warning if both of them are selected.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 289, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python3.5/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.5/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/usr/local/lib/python3.5/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.5/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.5/site-packages/django/template/library.py", line 201, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.5/site-packages/webpack_loader/templatetags/webpack_loader.py", line 40, in render_bundle
    return render_as_tags(_get_bundle(bundle_name, extension, config))
  File "/usr/local/lib/python3.5/site-packages/webpack_loader/templatetags/webpack_loader.py", line 32, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/usr/local/lib/python3.5/site-packages/webpack_loader/loader.py", line 54, in get_bundle
    assets = self.get_assets()
  File "/usr/local/lib/python3.5/site-packages/webpack_loader/loader.py", line 33, in get_assets
    return self._load_assets()
  File "/usr/local/lib/python3.5/site-packages/webpack_loader/loader.py", line 26, in _load_assets
    self.config['STATS_FILE']))
OSError: Error reading /app/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?
```

**Comment by goldhand** [comment]
Nodejs needs to be available for the npm commands to work (the missing `webpack-stats.json` is generated when you run `npm start`). I'm not very familiar with docker but I can look into including node somehow.

**Comment by jayfk** [comment]
Thanks! This was more of a reminder for myself than a call to action :)

I've managed to create a working hybrid setup with python running in docker and node running locally.
I'd love to move node into it's own container tough. There are some missing parts to do that:

- the node server has to be started on `0.0.0.0`
- there needs to be a command to run the node server on it's own, without calling `python manage.py runserver`. I've tried to run `node run dev`, but this didn't work.
- I need to find a way to safely bake `npm install` into the image.

**Comment by OkuraSt** [comment]
I´m not using docker, just webpack on a windows machine, and having this same error. First I changed the start script adding SET to NODE_ENV and it was able to start without errors, but when I request any route it fails. Any advice?
Thanks

**Comment by goldhand** [comment]
@OkuraSt I'm not familiar with windows machines so any troubleshooting you do would be helpful information to make this webpack setup work better with windows.

That's react-router intercepting the routes. There's a redirect you can remove in `routes.js` that will stop this behavior.

It might be a good idea to remove react-router from the webpack project because it really depends on how you want to configure your project to route. If you want to use react to control routes it makes sense to use it but if you're using django for routes you may not want to use react-router.

**Comment by vmitinskiy** [comment]
@jayfk do you found way to use docker with webpack together? Can you tell me how to do this or show me config files? I mean 

> a working hybrid setup with python running in docker and node running locally

Thank you.

ps sorry for my English

**Comment by ssteinerx** [comment]
@jayfk  Is this now moot since the webpack/react extravaganza has been removed from the main project?
