### ISSUE TITLE
Error when setting up cookiecutter: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by qasimalbaqali** [pydanny/cookiecutter-django#687]
This is the traceback that I get when trying to set up cookiecutter project:

```
(venv)project_x $cookiecutter https://github.com/pydanny/cookiecutter-django
Traceback (most recent call last):
  File "/Users/qasimalbaqali/Projects/project_x/venv/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/Users/qasimalbaqali/Projects/project_x/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/qasimalbaqali/Projects/project_x/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/qasimalbaqali/Projects/project_x/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/qasimalbaqali/Projects/project_x/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/qasimalbaqali/Projects/project_x/venv/lib/python2.7/site-packages/cookiecutter/cli.py", line 106, in main
    config_file=user_config
  File "/Users/qasimalbaqali/Projects/project_x/venv/lib/python2.7/site-packages/cookiecutter/main.py", line 107, in cookiecutter
    no_input=no_input
  File "/Users/qasimalbaqali/Projects/project_x/venv/lib/python2.7/site-packages/cookiecutter/vcs.py", line 102, in clone
    if not is_vcs_installed(repo_type):
  File "/Users/qasimalbaqali/Projects/project_x/venv/lib/python2.7/site-packages/cookiecutter/vcs.py", line 80, in is_vcs_installed
    return bool(which(repo_type))
  File "/Users/qasimalbaqali/Projects/project_x/venv/lib/python2.7/site-packages/whichcraft.py", line 71, in which
    name = os.path.join(dir, thefile)
  File "/Users/qasimalbaqali/Projects/project_x/venv/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

Tried to search around, and nothing came up that would solve it. Any ideas by anyone that encountered such a problem?

**Comment by luzfcb** [comment]
@qasimalbaqali 
Whats is your:
1 - python version: `python2 --version`
2 - cookiecutter version: `cookiecutter --version`
3 - the error occur if you install cookiecutter on python3 virtualenv and try again to run cookiecutter?
4 - what is the output of `cookiecutter --verbose https://github.com/pydanny/cookiecutter-django.git`

**Comment by qasimalbaqali** [comment]
@luzfcb using virtualenv python3 fixed it!

**Comment by luzfcb** [comment]
@qasimalbaqali ok, but cookiecutter should work with python2. 
you could provide information about questions 1, 2 and 4

**Comment by qasimalbaqali** [comment]
@luzfcb I'll to recreate the problem later and will post the answers for those questions 👍

**Comment by jayfk** [comment]
Looks like your path contains non-ascii characters. Could you run `ls -la` in the directory where you place your cookiecutter projects?

**Comment by jayfk** [comment]
I'm sorry, I meant `pwd`.

**Comment by qasimalbaqali** [comment]
@jayfk 
```
$ pwd
/Users/qasimalbaqali/Projects
```

**Comment by jayfk** [comment]
hmm, this looks right. Out of ideas :/
