### ISSUE TITLE
ImportError: No module named when trying to set-up 3rd party package.

### ISSUE THREAD

**Issue by qasimalbaqali** [pydanny/cookiecutter-django#692]
Trying to install and setup django-admin-timestamps. I already installed it through pip and using `pip freeze` I can see it is installed in my virtualenv

```
(venv3) $ pip freeze
..
django-admin-timestamps==1.2
...
```

and of course I put the package name under common.py settings 

```
THIRD_PARTY_APPS = (
    'crispy_forms',  # Form layouts
    'allauth',  # registration
    'allauth.account',  # registration
    'allauth.socialaccount',  # registration
    'django-admin-timestamps', # model timestamps
)
```

but when I try to run `makemigrations` I get the following traceback error:

```
(venv3) $ python ../manage.py makemigrations
Traceback (most recent call last):
  File "../manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/qasimalbaqali/Projects/project_x/venv3/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/qasimalbaqali/Projects/project_x/venv3/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Users/qasimalbaqali/Projects/project_x/venv3/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/qasimalbaqali/Projects/project_x/venv3/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/qasimalbaqali/Projects/project_x/venv3/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/qasimalbaqali/Projects/project_x/venv3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'django-admin-timestamps'
```

It happened earlier when I tried to register my own app the one that was created with `startapp` and I just needed to put the full path for it to be registered as in instead of `polls` I had to write `project_x.polls`.

**Comment by qasimalbaqali** [comment]
This is just a stupid mistake by me, I don't need to add djang-admin-timestamps as a package to the INSTALLED_APS I can just directly use it through importing it. Ignore me lol
