### ISSUE TITLE
Dockerfile-dev -- no initial migration leaves app inoperable

### ISSUE THREAD

**Issue by ssteinerx** [pydanny/cookiecutter-django#705]
On the first: 

      docker-compose up

the Postgres database is completely empty and the app, obviously, can't do much.

Somewhere (after Postgres has gotten its act together), we'll have to run:

    python manage.py migrate

I'll try it by hand for now due to #602.

**Comment by ssteinerx** [comment]
Running:
    d exec -ti propgen_django_1  /bin/bash

Gets me a shell, but trying to run the migration manually with:

    python manage.py migrate

Gives this:
```
root@270468381a2d:/app# python manage.py migrate
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

**Comment by jayfk** [comment]
Check the docs on [running management commands](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html#running-management-commands).

Just run

```
docker-compose -f dev.yml run django python manage.py migrate
```

**Comment by ssteinerx** [comment]
Sorry, missed that.
