### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by thaxy** [pydanny/cookiecutter-django#860]
```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\cookiecutter.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\cookiecutter\cli.py", line 100, in main
    config_file=user_config
  File "c:\python27\lib\site-packages\cookiecutter\main.py", line 140, in cookiecutter
    output_dir=output_dir
  File "c:\python27\lib\site-packages\cookiecutter\generate.py", line 327, in generate_files
    generate_file(project_dir, infile, context, env)
  File "c:\python27\lib\site-packages\cookiecutter\generate.py", line 167, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 786, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\python27\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File ".\LICENSE", line 3, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'now'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
  File ".\LICENSE", line 3
    Copyright (c) {% now 'utc', '%Y' %}, {{ cookiecutter.author_name }}
```

**Comment by jayfk** [comment]
https://github.com/pydanny/cookiecutter-django/issues/721

**Comment by thaxy** [comment]
Meh thanks for the support and sorry ;)
