### ISSUE TITLE
Error: object() takes no parameters with docker-compose up [--build]

### ISSUE THREAD

**Issue by oesah** [pydanny/cookiecutter-django#862]
Big trouble and I can't seem to find the solution. I installed Cookiecutter with Docker option. Now that I want to push it to production and get it running, I get the following error on production server with Ubuntu on Digital Ocean:

```
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 61, in __init__
    self.setup(app)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 120, in setup
    self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/app/config/wsgi.py", line 31, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
```

I spent several  hours on it now, but I cannot find the problem. Any suggestions? Do you need more Info?

**Comment by luzfcb** [comment]
@oesah you include some additional django app in the generated project?

what the exact sequence of options you used to generate the project?

this seems to be a problem related to compatibility with the new Django 1.10 Middleware

https://docs.djangoproject.com/en/1.10/topics/http/middleware/

**Comment by oesah** [comment]
So I tried to get a new, unmodified version running on the server without any third party modules. That worked properly. I found out, that Django Celery and Raven caused some errors. After upgrading Raven to the newest version and excluding celery from the stack, it works. I will investigate further and report here, for people running into the same problems.

**Comment by brentpayne** [comment]
I had the same issue with heroku.  It is an issue with Sentry's middleware in the included raven implimentation.  Change `raven==5.30.0` to `raven==5.31.0`.  I just put in a pull request for this.

**Comment by oesah** [comment]
Yeah I did, that seemed to fix the issue. Issue can be closed from my side.

**Comment by dmarcelino** [comment]
Thanks @brentpayne, that fixed the issue for me.
