### ISSUE TITLE
Environ 

### ISSUE THREAD

**Issue by plgitlogin** [pydanny/cookiecutter-django#965]
Problems with the environ package when doing 
cookiecutter https://github.com/pydanny/cookiecutter-django

project_name [Project Name]: cookeddjango      
project_slug [cookeddjango]: 
author_name [Daniel Roy Greenfeld]: D R G
email [you@example.com]: --@univ-mlv.fr
description [A short description of the project.]: Cookie django for poodle
domain_name [example.com]: umlv.fr
version [0.1.0]: 
timezone [UTC]: CTE
use_whitenoise [y]: y
use_celery [n]: 
use_mailhog [n]: 
use_sentry_for_error_reporting [y]: 
use_opbeat [n]: 
use_pycharm [n]: 
windows [n]: 
use_python3 [y]: 
use_docker [y]: n
use_heroku [n]: 
use_elasticbeanstalk_experimental [n]: 
use_compressor [n]: 
Select postgresql_version:
1 - 9.6
2 - 9.5
3 - 9.4
4 - 9.3
5 - 9.2
Choose from 1, 2, 3, 4, 5 [1]: 2
Select js_task_runner:
1 - Gulp
2 - Grunt
3 - None
Choose from 1, 2, 3 [1]: 1
use_lets_encrypt [n]: 
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]: 1
(env) MBPdeDominique3:cookeddjango dr$ python manage.py test
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/dr/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/dr/POODLE/SANDBOX/cookeddjango/config/settings/local.py", line 15, in <module>
    from .common import *  # noqa
  File "/Users/dr/POODLE/SANDBOX/cookeddjango/config/settings/common.py", line 13, in <module>
    import environ
ImportError: No module named 'environ'
(env) MBPdeDominique3:cookeddjango dr$ pip install environ
Collecting environ
Installing collected packages: environ
Successfully installed environ-1.0
(env) MBPdeDominique3:cookeddjango dr$ python manage.py test
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/dr/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/dr/POODLE/SANDBOX/cookeddjango/config/settings/local.py", line 15, in <module>
    from .common import *  # noqa
  File "/Users/dr/POODLE/SANDBOX/cookeddjango/config/settings/common.py", line 13, in <module>
    import environ
  File "/Users/dr/POODLE/SANDBOX/env/lib/python3.5/site-packages/environ.py", line 114
    raise ValueError, "No frame marked with %s." % fname
                    ^
SyntaxError: invalid syntax

**Comment by luzfcb** [comment]
I think that you probably install a wrong package.

Since, python does not force the package name to be the same as the python
module name, do not rely on the functionality of the IDE's to automatically
install the packages.

Load your virtualenv and run:

pip uninstall environ

pip install django-environ -U


All other packages are listed on requirements folder. Install all packages
on your virtualenv

If this solve the problem, please, close this issue

Em 30/12/2016 09:36, "plgitlogin" <notifications@github.com> escreveu:

**Comment by plgitlogin** [comment]
Ok 
thanks
