### ISSUE TITLE
Issue on first run

### ISSUE THREAD

**Issue by janssja** [pydanny/cookiecutter-django#972]
Hi,
I'm just following the instructions in the readme and received an error:
```
/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/environ/environ.py:617: UserWarning: Error reading /Users/jackie/Desktop/projects/djang-cookiecutter/reddit_clone/.env - if you're not configuring your environment separately, check this.
  "environment separately, check this." % env_file)
Traceback (most recent call last):
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 20, in <module>
    import psycopg2 as Database
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/psycopg2/_psycopg.cpython-35m-darwin.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/psycopg2/_psycopg.cpython-35m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/db/models/base.py", line 119, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 24, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: dlopen(/Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/psycopg2/_psycopg.cpython-35m-darwin.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/jackie/Desktop/projects/djang-cookiecutter/lib/python3.5/site-packages/psycopg2/_psycopg.cpython-35m-darwin.so
  Reason: image not found
```
Any advice?
Regards,
Jackie

**Comment by pydanny** [comment]
1. Do you have PostgreSQL installed on your Mac?
2. Is PostgreSQL running when you try to run the management command?

**Comment by pydanny** [comment]
Marked as closed. Please reopen if there is still a problem.
